---
title: "Hoped for Charminar, Stuck with Webinar"
author:  "[Housecat](https://www.linkedin.com/in/g-arvind-kumar/) on 27 July 2020"
output:
  html_document: 
    fig_width: 1
    toc: false
    toc_float: false
  
---

----

# <font color="ED820E"> **What's This Blog About?** </font>

<font size=4>

I started this blog out of boredom concomitant with online classes & webinars. 

I really hoped that studying in Hyderabad would allow me to rediscover my inner carnivore. 

Instead, I'm stuck indoors & mostly find myself staring at my laptop screen when I'm awake.

And, of the many extraordinary qualities I possess, asking stupid questions is the one which
I'm really proud of :)

Such a quality is deemed valuable in a __"slave to an excessively inquiring mind"__, or so I am told.

So, on this small nook of the world wide web, you'll find posts on -

- What I have been reading - I usually read non-fiction & occasionally fiction

- Some tidbits related to my academic interests & a few lazy hacks

</font>

# <font color="ED820E"> **Recent Posts** </font>

<center>

## 2020

### <font color="8F223A"> August </font>

<font size=4>

<font color="#0F5499">

__[BC-001] [Upcoming]__ _A Republic in the Making: India in the 1950s by Gyanesh Kudaisya_

</font>

### <font color="8F223A"> July </font>

<font size=4>

[__[HK-001]__ How to learn from Coursera MOOCs offered in a language you don't know?](https://octaveone.github.io/mwb/coursera_language_fix.html)

</font>

</center>

<br>
<br>

[***G Arvind Kumar, 2020 © ***](https://www.linkedin.com/in/g-arvind-kumar/) |  [***Contact - ✉***](mailto:itikilimitikily@gmail.com)


